export interface CourseItem {
  id: string;
  title: string;
  category: 'Diplomas & AI' | 'Software & Web Dev' | 'Accounting' | 'Office & Productivity' | 'Graphic & DTP';
  badge?: string;
  duration: string;
  description: string;
  iconName: string;
  popular?: boolean;
  syllabus: string[];
  prerequisites?: string;
  outcome: string;
}

export const coursesData: CourseItem[] = [
  {
    id: 'pgdca',
    title: 'PGDCA (Post Graduate Diploma in Computer Applications)',
    category: 'Diplomas & AI',
    badge: '1 Year Diploma',
    duration: '1 Year / 6 Months Fast-Track',
    description: 'Comprehensive computer diploma covering fundamentals, MS Office, accounting software, C/C++ programming, database management, and web applications.',
    iconName: 'GraduationCap',
    popular: true,
    syllabus: [
      'Computer Fundamentals & Operating Systems (Windows/Linux)',
      'MS Office Masterclass (Word, Excel, PowerPoint, Access)',
      'Tally Prime with GST Accounting',
      'C & C++ Programming Concepts',
      'Database Management Systems (DBMS / SQL)',
      'Web Fundamentals (HTML5, CSS, Internet Services)',
    ],
    prerequisites: '10th / 12th Pass or Graduate in any stream',
    outcome: 'Govt & Private Job Ready Computer Certification',
  },
  {
    id: 'fullstack-web',
    title: 'Full-Stack Frontend Web Development (React & Angular)',
    category: 'Software & Web Dev',
    badge: 'Career Track',
    duration: '3 to 6 Months',
    description: 'Master modern user interface development with HTML5, CSS3, JavaScript (ES6+), React.js, Angular, Tailwind CSS, and responsive design.',
    iconName: 'Code',
    popular: true,
    syllabus: [
      'HTML5 Semantic Markup & Modern CSS3 Layouts',
      'JavaScript (ES6+, Async/Await, DOM Manipulation)',
      'React.js (Hooks, State Management, Router, Context)',
      'Angular Fundamentals & Component Architecture',
      'Tailwind CSS & Responsive UI Design',
      'Git, GitHub, & Vercel/Netlify Deployment',
    ],
    prerequisites: 'Basic Computer Knowledge & Logical Aptitude',
    outcome: 'Build modern responsive web applications & websites',
  },
  {
    id: 'backend-node',
    title: 'Backend Web Development (Node.js & Databases)',
    category: 'Software & Web Dev',
    badge: 'In-Demand',
    duration: '3 Months',
    description: 'Learn server-side programming with Node.js, Express.js, RESTful API design, MongoDB & SQL database management, authentication, and security.',
    iconName: 'Server',
    popular: false,
    syllabus: [
      'Node.js Runtime & Event Loop Architecture',
      'Express.js Framework & Middleware Design',
      'RESTful API Building & Postman Testing',
      'MongoDB & Mongoose ORM Database Modeling',
      'SQL / PostgreSQL Queries & Relational DBs',
      'User Authentication (JWT, Bcrypt, Sessions)',
    ],
    prerequisites: 'Basic JavaScript Knowledge',
    outcome: 'Design and deploy secure scalable backend server APIs',
  },
  {
    id: 'devops-cloud',
    title: 'DevOps & Cloud Deployment Fundamentals',
    category: 'Software & Web Dev',
    badge: 'Modern Tech',
    duration: '2 to 3 Months',
    description: 'Understand modern software deployment pipelines, Docker containerization, CI/CD automation, version control, and cloud hosting.',
    iconName: 'Cpu',
    popular: false,
    syllabus: [
      'Git Version Control & Branching Strategies',
      'Docker Containers & Multi-container Compose',
      'Continuous Integration & Deployment (CI/CD)',
      'Linux Command Line & Shell Scripting',
      'Cloud Hosting Basics (AWS, Vercel, Docker Hub)',
    ],
    prerequisites: 'Basic Programming or Web Development Knowledge',
    outcome: 'Automate code build, testing, and cloud deployment pipelines',
  },
  {
    id: 'tally-gst',
    title: 'Tally Prime with GST & Financial Accounting',
    category: 'Accounting',
    badge: 'Industry Standard',
    duration: '2 to 3 Months',
    description: 'Complete hands-on accounting course covering Tally Prime, GST invoicing, tax calculations, voucher entry, inventory, and payroll.',
    iconName: 'Calculator',
    popular: true,
    syllabus: [
      'Fundamentals of Double-Entry Bookkeeping',
      'Tally Prime Interface & Company Creation',
      'GST Setup, IGST/CGST/SGST Tax Calculation',
      'Sales/Purchase Invoicing & Credit/Debit Notes',
      'Inventory Management & Stock Keeping',
      'Financial Reports: Trial Balance, P&L, Balance Sheet',
    ],
    prerequisites: 'Basic Mathematics & Computer Familiarity',
    outcome: 'Work as Accountant, Tally Operator, or Billing Specialist',
  },
  {
    id: 'ms-office',
    title: 'MS Office Masterclass (Word, Advanced Excel, PowerPoint)',
    category: 'Office & Productivity',
    badge: 'Essential Skill',
    duration: '1 to 2 Months',
    description: 'Master Microsoft Word document formatting, Advanced Excel formulas & data analysis (VLOOKUP, Pivot Tables), and dynamic PowerPoint presentations.',
    iconName: 'FileSpreadsheet',
    popular: true,
    syllabus: [
      'MS Word: Professional Formatting, Mail Merge, Reports',
      'MS Excel: Advanced Formulas (VLOOKUP, XLOOKUP, IF/AND)',
      'MS Excel: Pivot Tables, Charts, Data Validation, Filtering',
      'MS PowerPoint: Slide Master, Animations, Transitions',
      'Cloud File Management (Google Drive, OneDrive, PDFs)',
    ],
    prerequisites: 'Open to All Beginners',
    outcome: 'Proficiency in office tasks, administrative work & data entry',
  },
  {
    id: 'graphic-dtp',
    title: 'Graphic Design & DTP (Photoshop, PageMaker, CorelDraw)',
    category: 'Graphic & DTP',
    badge: 'Creative Skill',
    duration: '2 to 3 Months',
    description: 'Practical graphic design and desktop publishing course for photo editing, banner creation, marriage cards, flex banners, and book publishing.',
    iconName: 'Palette',
    popular: false,
    syllabus: [
      'Adobe Photoshop: Photo Editing, Layers, Retouching, Banners',
      'Adobe PageMaker: Book Layout, Typing, Document Publishing',
      'CorelDraw: Vector Art, Logo Design, Visiting Cards, Flex Banners',
      'Odia / English Typing & Font Conversion Tools',
      'Print Exporting (PDF, CMYK, High-Res Printing Rules)',
    ],
    prerequisites: 'Creative Mindset & Basic Computer Literacy',
    outcome: 'Start freelancing or work in Flex/Press/Graphic shops',
  },
  {
    id: 'ai-tools',
    title: 'AI Tools & Modern Productivity Masterclass',
    category: 'Diplomas & AI',
    badge: 'Trending 2026',
    duration: '1 Month',
    description: 'Learn how to leverage AI tools (ChatGPT, Claude, AI Image/Design tools, AI Resume Builders) to boost productivity, write content, and automate tasks.',
    iconName: 'Sparkles',
    popular: true,
    syllabus: [
      'ChatGPT & Claude: Effective Prompt Engineering Hacks',
      'AI Tools for Email Writing, Resume & CV Creation',
      'AI Image Generators & Creative Banner Prompts',
      'AI Excel Formula & Data Analysis Assistants',
      'Daily Workplace Automation & Time-Saving Tools',
    ],
    prerequisites: 'Basic Computer & Internet Usage',
    outcome: 'Save hours daily using cutting-edge artificial intelligence',
  },
];
